const https = require('https');
require('dotenv').config();

const PROJECT_REF = process.env.SUPABASE_PROJECT_REF;
const ACCESS_TOKEN = process.env.SUPABASE_ACCESS_TOKEN;

if (!PROJECT_REF || !ACCESS_TOKEN) {
  console.error('❌ Missing SUPABASE_PROJECT_REF or SUPABASE_ACCESS_TOKEN in .env');
  process.exit(1);
}

function runSQL(sql, label) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({ query: sql });
    const options = {
      hostname: 'api.supabase.com',
      path: `/v1/projects/${PROJECT_REF}/database/query`,
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${ACCESS_TOKEN}`,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(body),
      },
    };
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode >= 400) {
          console.error(`[${label}] Error (${res.statusCode}):`, data.substring(0, 300));
          reject(new Error(`HTTP ${res.statusCode}`));
        } else {
          console.log(`[${label}] ✅`);
          resolve(data);
        }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

// Build INSERT SQL for lectures
function buildLectureInserts(rows) {
  const vals = rows.map(r => {
    const desc = (r.desc || '').replace(/'/g, "''");
    const title = r.title.replace(/'/g, "''");
    return `((SELECT id FROM subjects WHERE name = '${r.subject}'), ${r.cls}, ${r.ch}, '${title}', '${desc}', ${r.dur || 30}, ${r.order || r.ch})`;
  });
  return `INSERT INTO lectures (subject_id, class_level, chapter_number, title, description, duration_minutes, display_order) VALUES\n${vals.join(',\n')}\nON CONFLICT DO NOTHING;`;
}

const lectureData = {

  // ─── CLASS 6 ───────────────────────────────────────────────
  '6-Mathematics': [
    {ch:1, title:'Knowing Our Numbers', desc:'Understanding large numbers, place value, comparing and ordering numbers'},
    {ch:2, title:'Whole Numbers', desc:'Number line, properties of whole numbers, patterns'},
    {ch:3, title:'Playing with Numbers', desc:'Factors, multiples, HCF, LCM, prime and composite numbers'},
    {ch:4, title:'Basic Geometrical Ideas', desc:'Points, lines, line segments, angles, curves, polygons and circles'},
    {ch:5, title:'Understanding Elementary Shapes', desc:'Measuring line segments, angles, triangles, quadrilaterals and polygons'},
    {ch:6, title:'Integers', desc:'Negative numbers, number line, addition and subtraction of integers'},
    {ch:7, title:'Fractions', desc:'Proper, improper and mixed fractions, equivalent fractions, operations'},
    {ch:8, title:'Decimals', desc:'Tenths, hundredths, comparing decimals, addition and subtraction'},
    {ch:9, title:'Data Handling', desc:'Recording data, pictograph, bar graph, interpretation'},
    {ch:10, title:'Mensuration', desc:'Perimeter of rectangles, squares, triangles and area'},
    {ch:11, title:'Algebra', desc:'Introduction to variables, expressions and simple equations'},
    {ch:12, title:'Ratio and Proportion', desc:'Ratio, proportion, unitary method'},
    {ch:13, title:'Symmetry', desc:'Line of symmetry, lines of symmetry in regular polygons'},
    {ch:14, title:'Practical Geometry', desc:'Drawing lines, circles, angles using compass and ruler'},
  ],
  '6-Science': [
    {ch:1, title:'Food: Where Does It Come From?', desc:'Sources of food, plant and animal products, herbivores and carnivores'},
    {ch:2, title:'Components of Food', desc:'Nutrients, carbohydrates, proteins, fats, vitamins, minerals and water'},
    {ch:3, title:'Fibre to Fabric', desc:'Plant fibres, cotton and jute, spinning and weaving'},
    {ch:4, title:'Sorting Materials into Groups', desc:'Properties of materials, transparency, solubility, grouping objects'},
    {ch:5, title:'Separation of Substances', desc:'Methods of separation: hand picking, threshing, winnowing, sieving, evaporation'},
    {ch:6, title:'Changes Around Us', desc:'Reversible and irreversible changes, physical and chemical changes'},
    {ch:7, title:'Getting to Know Plants', desc:'Herbs, shrubs, trees, roots, stems, leaves, flowers'},
    {ch:8, title:'Body Movements', desc:'Types of joints, human skeleton, movement in animals'},
    {ch:9, title:'The Living Organisms and Their Surroundings', desc:'Habitat, adaptation, biotic and abiotic components'},
    {ch:10, title:'Motion and Measurement of Distances', desc:'Standard units, measuring length, types of motion'},
    {ch:11, title:'Light, Shadows and Reflections', desc:'Sources of light, transparent and opaque objects, shadows, mirrors'},
    {ch:12, title:'Electricity and Circuits', desc:'Electric cell, bulb, switch, conductors and insulators'},
    {ch:13, title:'Fun with Magnets', desc:'Magnetic and non-magnetic materials, poles, compass'},
    {ch:14, title:'Water', desc:'Water cycle, sources of water, conservation and management'},
    {ch:15, title:'Air Around Us', desc:'Composition of air, wind, oxygen and nitrogen'},
    {ch:16, title:'Garbage In, Garbage Out', desc:'Waste management, composting, recycling, reducing garbage'},
  ],
  '6-Social Science': [
    {ch:1, title:'What, Where, How and When?', desc:'Sources of history, finding out about the past, manuscripts and inscriptions'},
    {ch:2, title:'From Hunting-Gathering to Growing Food', desc:'Early humans, the Neolithic age, domestication of animals'},
    {ch:3, title:'In the Earliest Cities', desc:'Harappan civilisation, town planning, trade and crafts'},
    {ch:4, title:'What Books and Burials Tell Us', desc:'The Vedas, megalithic burials, iron tools'},
    {ch:5, title:'Kingdoms, Kings and an Early Republic', desc:'Janapadas, Mahajanapadas, republics'},
    {ch:6, title:'The Earth in the Solar System', desc:'Planets, sun, moon, stars, constellations, the solar system'},
    {ch:7, title:'Globe: Latitudes and Longitudes', desc:'Rotation, parallels of latitude, meridians of longitude, time zones'},
    {ch:8, title:'Motions of the Earth', desc:'Rotation, revolution, seasons, solstice and equinox'},
    {ch:9, title:'Maps', desc:'Types of maps, components: distance, direction, symbol'},
    {ch:10, title:'Major Domains of the Earth', desc:'Lithosphere, hydrosphere, atmosphere, biosphere'},
  ],
  '6-English': [
    {ch:1, title:'A Tale of Two Birds', desc:'Reading comprehension, vocabulary and grammar exercises'},
    {ch:2, title:'The Friendly Mongoose', desc:'Story comprehension, character analysis, adjectives'},
    {ch:3, title:'The Shepherd\'s Treasure', desc:'Honesty and values, comprehension, past tense verbs'},
    {ch:4, title:'The Old Clock Shop', desc:'Narrative reading, comprehension, question formation'},
    {ch:5, title:'Tansen', desc:'Biography, great musician of Akbar\'s court, comprehension'},
    {ch:6, title:'The Monkey and the Crocodile', desc:'Fable, moral lesson, comprehension and vocabulary'},
    {ch:7, title:'The Wonder Called Sleep', desc:'Informational text, facts about sleep, comprehension'},
    {ch:8, title:'A Pact with the Sun', desc:'Story of Saeeda and her mother, comprehension, values'},
  ],
  '6-Hindi': [
    {ch:1, title:'वह चिड़िया जो', desc:'कविता - वसंत भाग 1, भावार्थ और प्रश्नोत्तर'},
    {ch:2, title:'बचपन', desc:'संस्मरण, कृष्णा सोबती, बचपन की यादें'},
    {ch:3, title:'नादान दोस्त', desc:'कहानी, प्रेमचंद, दोस्ती और समझदारी'},
    {ch:4, title:'चाँद से थोड़ी सी गप्पें', desc:'कविता, शमशेर बहादुर सिंह, भावार्थ'},
    {ch:5, title:'अक्षरों का महत्व', desc:'निबंध, लेखन कला का इतिहास'},
    {ch:6, title:'पार नज़र के', desc:'कहानी, जयंत विष्णु नार्लीकर, विज्ञान कथा'},
    {ch:7, title:'साथी हाथ बढ़ाना', desc:'गीत, साहित्य अकादमी, श्रम और सहयोग'},
    {ch:8, title:'ऐसे–ऐसे', desc:'एकांकी, विनोद रस और हास्य'},
  ],

  // ─── CLASS 7 ───────────────────────────────────────────────
  '7-Mathematics': [
    {ch:1, title:'Integers', desc:'Properties of integers, multiplication and division of integers'},
    {ch:2, title:'Fractions and Decimals', desc:'Multiplication and division of fractions and decimals'},
    {ch:3, title:'Data Handling', desc:'Mean, median, mode, bar graphs, chance and probability'},
    {ch:4, title:'Simple Equations', desc:'Setting up equations, solving linear equations'},
    {ch:5, title:'Lines and Angles', desc:'Related angles, pairs of lines, transversal, parallel lines'},
    {ch:6, title:'The Triangle and Its Properties', desc:'Medians, altitudes, exterior angle, angle sum property, Pythagoras'},
    {ch:7, title:'Congruence of Triangles', desc:'Criteria for congruence: SSS, SAS, ASA, RHS'},
    {ch:8, title:'Comparing Quantities', desc:'Ratios, percentages, profit, loss, simple interest'},
    {ch:9, title:'Rational Numbers', desc:'Need for rational numbers, positive and negative rationals, number line'},
    {ch:10, title:'Practical Geometry', desc:'Construction of triangles with given conditions'},
    {ch:11, title:'Perimeter and Area', desc:'Area of parallelogram, triangle, circle, converting units'},
    {ch:12, title:'Algebraic Expressions', desc:'Terms, factors, coefficients, like and unlike terms, addition'},
    {ch:13, title:'Exponents and Powers', desc:'Laws of exponents, expressing large numbers in standard form'},
    {ch:14, title:'Symmetry', desc:'Lines of symmetry, rotational symmetry, centre of rotation'},
    {ch:15, title:'Visualising Solid Shapes', desc:'3D shapes, nets, vertices, edges, faces, cross sections'},
  ],
  '7-Science': [
    {ch:1, title:'Nutrition in Plants', desc:'Mode of nutrition, photosynthesis, other modes of nutrition'},
    {ch:2, title:'Nutrition in Animals', desc:'Digestion in humans, grass-eating animals, feeding in amoeba'},
    {ch:3, title:'Fibre to Fabric', desc:'Wool, silk, rearing and breeding of silkworms'},
    {ch:4, title:'Heat', desc:'Hot and cold, measuring temperature, conduction, convection, radiation'},
    {ch:5, title:'Acids, Bases and Salts', desc:'Natural indicators, neutralisation, everyday uses'},
    {ch:6, title:'Physical and Chemical Changes', desc:'Rusting, crystallisation, types of changes'},
    {ch:7, title:'Weather, Climate and Adaptations', desc:'Weather, climate zones, adaptation in animals'},
    {ch:8, title:'Winds, Storms and Cyclones', desc:'Air pressure, wind patterns, thunderstorms, cyclones'},
    {ch:9, title:'Soil', desc:'Soil profile, types of soil, absorption of water, soil erosion'},
    {ch:10, title:'Respiration in Organisms', desc:'Breathing, respiration, aerobic and anaerobic respiration'},
    {ch:11, title:'Transportation in Animals and Plants', desc:'Circulatory system, blood, heart, excretion, transport in plants'},
    {ch:12, title:'Reproduction in Plants', desc:'Modes of reproduction, vegetative propagation, pollination, seed dispersal'},
    {ch:13, title:'Motion and Time', desc:'Slow and fast, speed, distance-time graph, measuring time'},
    {ch:14, title:'Electric Current and Its Effects', desc:'Symbols, heating effect, magnetic effect, electromagnet'},
    {ch:15, title:'Light', desc:'Light travels in straight line, reflection, mirrors, lenses, sunlight'},
    {ch:16, title:'Water: A Precious Resource', desc:'Groundwater, water cycle, water management'},
    {ch:17, title:'Forests: Our Lifeline', desc:'Forest ecosystem, canopy, decomposers, biodiversity'},
    {ch:18, title:'Wastewater Story', desc:'Sewage, treatment of wastewater, sanitation'},
  ],
  '7-Social Science': [
    {ch:1, title:'Tracing Changes Through a Thousand Years', desc:'New and old terminologies, historians and their sources, maps'},
    {ch:2, title:'New Kings and Kingdoms', desc:'Rise of new dynasties, administration, revenues, warfare'},
    {ch:3, title:'The Delhi Sultans', desc:'Finding out about the Delhi Sultans, administration and consolidation'},
    {ch:4, title:'The Mughal Empire', desc:'Babur to Aurangzeb, military campaigns, Mughal administration'},
    {ch:5, title:'Rulers and Buildings', desc:'Engineering skills, building temples and mosques, imperial vision'},
    {ch:6, title:'Towns, Traders and Craftspersons', desc:'Temple towns, administrative centres, traders, craftspersons'},
    {ch:7, title:'Tribes, Nomads and Settled Communities', desc:'Tribal societies, nomadic pastoralists, caste society'},
    {ch:8, title:'Environment', desc:'Natural environment, human environment, climate, flora and fauna'},
    {ch:9, title:'Inside Our Earth', desc:'Layers of earth, rocks, minerals, types of rocks, rock cycle'},
    {ch:10, title:'Our Changing Earth', desc:'Lithospheric plates, earthquakes, volcanoes, work of a river'},
    {ch:11, title:'Air', desc:'Composition of atmosphere, structure, weather, climate, seasons'},
    {ch:12, title:'Water', desc:'Water on Earth, ocean circulation, waves, tides, currents'},
  ],
  '7-English': [
    {ch:1, title:'Three Questions', desc:'Tolstoy story, the right time, the right people, the right thing to do'},
    {ch:2, title:'A Gift of Chappals', desc:'Family relationships, traditions, comprehension exercises'},
    {ch:3, title:'Gopal and the Hilsa Fish', desc:'Humour and wit, mission impossible, comprehension'},
    {ch:4, title:'The Ashes That Made Trees Bloom', desc:'Japanese story, kindness and generosity'},
    {ch:5, title:'Quality', desc:'The value of quality work by John Galsworthy'},
    {ch:6, title:'Expert Detectives', desc:'Mystery story, clues, deductive reasoning'},
    {ch:7, title:'The Invention of Vita-Wonk', desc:'Charlie and the Chocolate Factory excerpt, imagination'},
    {ch:8, title:'Fire: Friend and Foe', desc:'Informational text, uses and dangers of fire'},
    {ch:9, title:'A Bicycle in Good Repair', desc:'Humorous story, describing processes'},
    {ch:10, title:'The Story of Cricket', desc:'History of cricket, how the game evolved'},
  ],
  '7-Hindi': [
    {ch:1, title:'हम पंछी उन्मुक्त गगन के', desc:'कविता - शिवमंगल सिंह सुमन, स्वतंत्रता की कामना'},
    {ch:2, title:'दादी माँ', desc:'संस्मरण - शिवप्रसाद सिंह, दादी माँ का स्नेह'},
    {ch:3, title:'हिमालय की बेटियाँ', desc:'निबंध - नागार्जुन, नदियों का मानवीकरण'},
    {ch:4, title:'कठपुतली', desc:'कविता - भवानीप्रसाद मिश्र, स्वतंत्रता की इच्छा'},
    {ch:5, title:'मिठाईवाला', desc:'कहानी - भगवतीप्रसाद वाजपेयी, बच्चों से प्यार'},
    {ch:6, title:'रक्त और हमारा शरीर', desc:'निबंध, रक्त के महत्व की जानकारी'},
    {ch:7, title:'पापा खो गए', desc:'एकांकी - विजय तेंदुलकर, रोमांचक कहानी'},
    {ch:8, title:'शाम - एक किसान', desc:'कविता - सर्वेश्वर दयाल सक्सेना'},
  ],

  // ─── CLASS 8 ───────────────────────────────────────────────
  '8-Mathematics': [
    {ch:1, title:'Rational Numbers', desc:'Properties of rational numbers, number line, between two rational numbers'},
    {ch:2, title:'Linear Equations in One Variable', desc:'Solving equations with variables on both sides, reducing equations'},
    {ch:3, title:'Understanding Quadrilaterals', desc:'Polygons, sum of angles, parallelogram, rectangle, rhombus, square'},
    {ch:4, title:'Data Handling', desc:'Pie charts, probability, chance, organising data'},
    {ch:5, title:'Squares and Square Roots', desc:'Properties of square numbers, Pythagorean triplets, finding square roots'},
    {ch:6, title:'Cubes and Cube Roots', desc:'Finding cube roots through prime factorisation'},
    {ch:7, title:'Comparing Quantities', desc:'Recalling ratios and percentages, finding increase/decrease, compound interest'},
    {ch:8, title:'Algebraic Expressions and Identities', desc:'Monomials, binomials, polynomials, multiplication, standard identities'},
    {ch:9, title:'Mensuration', desc:'Area of trapezium, general quadrilateral, polygons, surface area, volume'},
    {ch:10, title:'Exponents and Powers', desc:'Powers with negative exponents, scientific notation, expressing in standard form'},
    {ch:11, title:'Direct and Inverse Proportions', desc:'Direct and inverse variation, solving problems'},
    {ch:12, title:'Factorisation', desc:'Factors of natural numbers and algebraic expressions, division of polynomials'},
    {ch:13, title:'Introduction to Graphs', desc:'Bar graphs, pie charts, histograms, line graphs, coordinates'},
    {ch:14, title:'Playing with Numbers', desc:'Numbers in general form, games with numbers, letters for digits'},
  ],
  '8-Science': [
    {ch:1, title:'Crop Production and Management', desc:'Agricultural practices, kharif and rabi crops, irrigation, fertilizers'},
    {ch:2, title:'Microorganisms: Friend and Foe', desc:'Types of microorganisms, useful and harmful microbes, food preservation'},
    {ch:3, title:'Synthetic Fibres and Plastics', desc:'Types of synthetic fibres, properties, plastics and environment'},
    {ch:4, title:'Materials: Metals and Non-Metals', desc:'Physical and chemical properties, uses, displacement reactions'},
    {ch:5, title:'Coal and Petroleum', desc:'Natural resources, coal, petroleum, natural gas, conservation'},
    {ch:6, title:'Combustion and Flame', desc:'Conditions for combustion, types of combustion, flame, fire control'},
    {ch:7, title:'Conservation of Plants and Animals', desc:'Deforestation, biodiversity, wildlife sanctuary, national parks'},
    {ch:8, title:'Cell: Structure and Functions', desc:'Discovery of cell, cell organelles, plant and animal cells'},
    {ch:9, title:'Reproduction in Animals', desc:'Sexual and asexual reproduction, human reproductive organs'},
    {ch:10, title:'Reaching the Age of Adolescence', desc:'Puberty, hormones, reproductive health, personal hygiene'},
    {ch:11, title:'Force and Pressure', desc:'Types of forces, pressure, atmospheric pressure, pressure in fluids'},
    {ch:12, title:'Friction', desc:'Factors affecting friction, advantages and disadvantages, rolling friction'},
    {ch:13, title:'Sound', desc:'Production, propagation, reflection of sound, echo, noise pollution'},
    {ch:14, title:'Chemical Effects of Electric Current', desc:'Electrolytes, electroplating, LED, applications'},
    {ch:15, title:'Some Natural Phenomena', desc:'Lightning, earthquakes, seismic zones, cyclone, precautions'},
    {ch:16, title:'Light', desc:'Laws of reflection, regular and irregular reflection, multiple images'},
    {ch:17, title:'Stars and the Solar System', desc:'Moon, stars, solar system, comets, man-made satellites'},
    {ch:18, title:'Pollution of Air and Water', desc:'Air and water pollutants, potable water, Ganga pollution'},
  ],
  '8-Social Science': [
    {ch:1, title:'How, When and Where?', desc:'Colonial records, James Mill, dates and periodization'},
    {ch:2, title:'From Trade to Territory', desc:'East India Company, trade, wars and administrations'},
    {ch:3, title:'Ruling the Countryside', desc:'Revenue systems, Permanent Settlement, Ryotwari, Mahalwari'},
    {ch:4, title:'Tribals, Dikus and the Vision of a Golden Age', desc:'Tribal societies and colonial rule, Birsa Munda'},
    {ch:5, title:'When People Rebel', desc:'1857 Revolt, sepoys, landlords, rulers, aftermath'},
    {ch:6, title:'Resources', desc:'Types of resources, natural resources, distribution and conservation'},
    {ch:7, title:'Land, Soil, Water, Natural Vegetation', desc:'Land use, soil types, water scarcity, conservation'},
    {ch:8, title:'Mineral and Power Resources', desc:'Types of minerals, power resources, conventional and non-conventional'},
    {ch:9, title:'Agriculture', desc:'Types of farming, crops, agricultural development'},
    {ch:10, title:'Industries', desc:'Classification of industries, factors of location, industrial systems'},
    {ch:11, title:'The Indian Constitution', desc:'Why a constitution, need for constitution, features of Indian constitution'},
    {ch:12, title:'Understanding Secularism', desc:'What is secularism, why India is secular, role of government'},
  ],
  '8-English': [
    {ch:1, title:'The Best Christmas Present in the World', desc:'Michael Morpurgo story, WWI, humanity in war'},
    {ch:2, title:'The Tsunami', desc:'Informational text, earthquake, tidal waves, animal instinct'},
    {ch:3, title:'Glimpses of the Past', desc:'Comic strip history, British rule, social reforms'},
    {ch:4, title:'Bepin Choudhury\'s Lapse of Memory', desc:'Satyajit Ray story, identity and memory'},
    {ch:5, title:'The Summit Within', desc:'Mountaineering, H.P.S. Ahluwalia, climbing Everest'},
    {ch:6, title:'This is Jody\'s Fawn', desc:'Marjorie Kinnan Rawlings, nature and friendship'},
    {ch:7, title:'A Visit to Cambridge', desc:'Meeting Stephen Hawking, disability and determination'},
    {ch:8, title:'A Short Monsoon Diary', desc:'Ruskin Bond, diary format, nature writing'},
  ],
  '8-Hindi': [
    {ch:1, title:'ध्वनि', desc:'कविता - सूर्यकांत त्रिपाठी निराला, प्रकृति और जीवन'},
    {ch:2, title:'लाख की चूड़ियाँ', desc:'कहानी - कामतानाथ, लाख के काम का ह्रास'},
    {ch:3, title:'बस की यात्रा', desc:'व्यंग्य - हरिशंकर परसाई, यात्रा का हास्यपूर्ण वर्णन'},
    {ch:4, title:'दीवानों की हस्ती', desc:'कविता - भगवतीचरण वर्मा, फक्कड़पन'},
    {ch:5, title:'चिट्ठियों की अनूठी दुनिया', desc:'निबंध - अरविंद कुमार सिंह, पत्र-लेखन का महत्व'},
    {ch:6, title:'भगवान के डाकिए', desc:'कविता - रामधारी सिंह दिनकर, पक्षी और बादल'},
    {ch:7, title:'क्या निराश हुआ जाए', desc:'निबंध - हजारीप्रसाद द्विवेदी, आशावाद'},
    {ch:8, title:'यह सबसे कठिन समय नहीं', desc:'कविता - जया जादवानी, कठिन समय में आशा'},
  ],

  // ─── CLASS 9 ───────────────────────────────────────────────
  '9-Mathematics': [
    {ch:1, title:'Number Systems', desc:'Irrational numbers, real numbers, real number line, surds, laws of exponents'},
    {ch:2, title:'Polynomials', desc:'Polynomials in one variable, zeroes, remainder theorem, factor theorem'},
    {ch:3, title:'Coordinate Geometry', desc:'Cartesian system, plotting points, naming quadrants'},
    {ch:4, title:'Linear Equations in Two Variables', desc:'Solutions, graph of linear equations, equations of lines parallel to axes'},
    {ch:5, title:'Introduction to Euclid\'s Geometry', desc:'Euclid\'s definitions, axioms, postulates, equivalent versions'},
    {ch:6, title:'Lines and Angles', desc:'Basic terms, intersecting lines, parallel lines, angle sum property of triangle'},
    {ch:7, title:'Triangles', desc:'Congruence criteria, properties of isosceles triangle, inequalities'},
    {ch:8, title:'Quadrilaterals', desc:'Angle sum property, properties of parallelogram, midpoint theorem'},
    {ch:9, title:'Areas of Parallelograms and Triangles', desc:'Figures on same base and between same parallels'},
    {ch:10, title:'Circles', desc:'Chord properties, angle subtended, equal chords, arc and angles'},
    {ch:11, title:'Constructions', desc:'Bisecting angles, perpendicular bisector, constructing triangles'},
    {ch:12, title:'Heron\'s Formula', desc:'Area of triangle using Heron\'s formula, quadrilateral areas'},
    {ch:13, title:'Surface Areas and Volumes', desc:'Cuboid, cube, right cylinder, right cone, sphere, hemisphere'},
    {ch:14, title:'Statistics', desc:'Collection and presentation of data, mean, median, mode, bar graphs'},
    {ch:15, title:'Probability', desc:'Experimental probability, complementary events'},
  ],
  '9-Science': [
    {ch:1, title:'Matter in Our Surroundings', desc:'Physical nature of matter, states of matter, evaporation'},
    {ch:2, title:'Is Matter Around Us Pure?', desc:'Mixtures, solutions, colloids, separating mixtures, physical changes'},
    {ch:3, title:'Atoms and Molecules', desc:'Laws of chemical combination, atoms, molecules, ions, mole concept'},
    {ch:4, title:'Structure of the Atom', desc:'Charged particles, Thomson\'s and Rutherford\'s models, Bohr model, valency'},
    {ch:5, title:'The Fundamental Unit of Life', desc:'Cell, plasma membrane, nucleus, cell organelles, plant vs animal cell'},
    {ch:6, title:'Tissues', desc:'Plant and animal tissues, functions'},
    {ch:7, title:'Motion', desc:'Distance, displacement, velocity, acceleration, equations of motion, graphs'},
    {ch:8, title:'Force and Laws of Motion', desc:'Newton\'s three laws, inertia, momentum, conservation'},
    {ch:9, title:'Gravitation', desc:'Universal law of gravitation, free fall, mass, weight, Archimedes\' principle'},
    {ch:10, title:'Work and Energy', desc:'Work done, energy, kinetic and potential energy, conservation of energy, power'},
    {ch:11, title:'Sound', desc:'Production and propagation, speed, reflection, echo, sonar, human ear'},
    {ch:12, title:'Improvement in Food Resources', desc:'Crop improvement, manure, fertilizers, crop protection, animal husbandry'},
  ],
  '9-Social Science': [
    {ch:1, title:'The French Revolution', desc:'Causes, events, Declaration of Rights of Man, Napoleon'},
    {ch:2, title:'Socialism in Europe and the Russian Revolution', desc:'Liberalism, socialism, Bolsheviks, Lenin, Stalin'},
    {ch:3, title:'Nazism and the Rise of Hitler', desc:'Weimar Republic, Nazi ideology, Holocaust, World War II'},
    {ch:4, title:'Forest Society and Colonialism', desc:'Colonial impact on forests, Java and India, Forest communities'},
    {ch:5, title:'Pastoralists in the Modern World', desc:'Pastoral communities, colonial rule, changes after independence'},
    {ch:6, title:'India - Size and Location', desc:'India\'s location, latitudinal and longitudinal extent, neighbours'},
    {ch:7, title:'Physical Features of India', desc:'Geological structure, major physiographic divisions, Himalayan ranges'},
    {ch:8, title:'Drainage', desc:'River systems, Himalayan rivers, Peninsular rivers, lakes'},
    {ch:9, title:'Climate', desc:'Factors influencing climate, monsoon, seasons, climate and Indian economy'},
    {ch:10, title:'Natural Vegetation and Wildlife', desc:'Types of vegetation, wildlife, conservation'},
    {ch:11, title:'Population', desc:'Population size, growth, distribution, composition, adolescents'},
    {ch:12, title:'What is Democracy? Why Democracy?', desc:'Features, arguments for and against democracy'},
    {ch:13, title:'Constitutional Design', desc:'Making the constitution, guiding values, Indian constitution'},
    {ch:14, title:'Electoral Politics', desc:'Elections, electoral competition, code of conduct, voters'},
    {ch:15, title:'The Story of Village Palampur', desc:'Farming, non-farm activities, capital and labour'},
  ],
  '9-English': [
    {ch:1, title:'The Fun They Had', desc:'Isaac Asimov science fiction, future schools, technology'},
    {ch:2, title:'The Sound of Music', desc:'Evelyn Glennie and Bismillah Khan, music and perseverance'},
    {ch:3, title:'The Little Girl', desc:'Katherine Mansfield, father-daughter relationship, fear'},
    {ch:4, title:'A Truly Beautiful Mind', desc:'Albert Einstein, genius, relativity, peace'},
    {ch:5, title:'The Snake and the Mirror', desc:'Humorous story, vanity, close encounter with a snake'},
    {ch:6, title:'My Childhood', desc:'A.P.J. Abdul Kalam, childhood memories, communal harmony'},
    {ch:7, title:'Reach for the Top', desc:'Santosh Yadav and Maria Sharapova, determination'},
    {ch:8, title:'Kathmandu', desc:'Vikram Seth, travelogue, Pashupatinath and Baudhnath'},
    {ch:9, title:'If I Were You', desc:'Drama, suspense, intruder and householder'},
  ],
  '9-Hindi': [
    {ch:1, title:'दो बैलों की कथा', desc:'कहानी - प्रेमचंद, हीरा और मोती की मित्रता, स्वतंत्रता'},
    {ch:2, title:'ल्हासा की ओर', desc:'यात्रावृत्त - राहुल सांकृत्यायन, तिब्बत यात्रा'},
    {ch:3, title:'उपभोक्तावाद की संस्कृति', desc:'निबंध - श्यामाचरण दुबे, उपभोक्ता संस्कृति की आलोचना'},
    {ch:4, title:'साँवले सपनों की याद', desc:'संस्मरण - जाबिर हुसेन, सालिम अली की याद'},
    {ch:5, title:'नाना साहब की पुत्री देवी मैना को भस्म कर दिया', desc:'चपला देवी, 1857 विद्रोह'},
    {ch:6, title:'प्रेमचंद के फटे जूते', desc:'व्यंग्य - हरिशंकर परसाई, आदर्श और व्यवहार'},
    {ch:7, title:'मेरे बचपन के दिन', desc:'संस्मरण - महादेवी वर्मा, बचपन की यादें'},
    {ch:8, title:'एक कुत्ता और एक मैना', desc:'निबंध - हजारीप्रसाद द्विवेदी, पशु-पक्षी प्रेम'},
    {ch:9, title:'साखियाँ एवं सबद', desc:'कविता - कबीर, भक्ति और ज्ञान'},
    {ch:10, title:'वाख', desc:'कविता - ललद्यद, कश्मीरी संत कवयित्री'},
  ],

  // ─── CLASS 10 ─────────────────────────────────────────────
  '10-Mathematics': [
    {ch:1, title:'Real Numbers', desc:'Euclid\'s division lemma, fundamental theorem of arithmetic, irrational numbers'},
    {ch:2, title:'Polynomials', desc:'Geometrical meaning of zeroes, relationship between zeroes and coefficients'},
    {ch:3, title:'Pair of Linear Equations in Two Variables', desc:'Graphical and algebraic methods of solution, consistency'},
    {ch:4, title:'Quadratic Equations', desc:'Standard form, factorisation, completing the square, quadratic formula'},
    {ch:5, title:'Arithmetic Progressions', desc:'AP, nth term, sum of n terms, applications'},
    {ch:6, title:'Triangles', desc:'Similarity, criteria for similarity, areas, Pythagoras theorem'},
    {ch:7, title:'Coordinate Geometry', desc:'Distance formula, section formula, area of triangle'},
    {ch:8, title:'Introduction to Trigonometry', desc:'Trigonometric ratios, complementary angles, identities'},
    {ch:9, title:'Some Applications of Trigonometry', desc:'Heights and distances, angle of elevation and depression'},
    {ch:10, title:'Circles', desc:'Tangent to circle, number of tangents from external point'},
    {ch:11, title:'Areas Related to Circles', desc:'Area of sector, segment, combinations of plane figures'},
    {ch:12, title:'Surface Areas and Volumes', desc:'Combination of solids, conversion of one solid to another'},
    {ch:13, title:'Statistics', desc:'Mean, median, mode of grouped data, cumulative frequency, ogive'},
    {ch:14, title:'Probability', desc:'Classical definition, simple problems, complementary events'},
  ],
  '10-Science': [
    {ch:1, title:'Chemical Reactions and Equations', desc:'Chemical equations, types of reactions, oxidation and reduction'},
    {ch:2, title:'Acids, Bases and Salts', desc:'Properties, pH scale, salts, plaster of Paris, baking soda'},
    {ch:3, title:'Metals and Non-metals', desc:'Physical and chemical properties, reactivity series, ionic bonds'},
    {ch:4, title:'Carbon and Its Compounds', desc:'Covalent bonds, versatile nature of carbon, important compounds, soaps'},
    {ch:5, title:'Life Processes', desc:'Nutrition, respiration, transportation and excretion in organisms'},
    {ch:6, title:'Control and Coordination', desc:'Animals: nervous system, reflex actions. Plants: tropisms, hormones'},
    {ch:7, title:'How do Organisms Reproduce?', desc:'Asexual and sexual reproduction, human reproductive system'},
    {ch:8, title:'Heredity and Evolution', desc:'Variation, Mendel\'s laws, sex determination, evolution, natural selection'},
    {ch:9, title:'Light: Reflection and Refraction', desc:'Reflection, mirrors, refraction, lenses, sign convention'},
    {ch:10, title:'The Human Eye and the Colourful World', desc:'Human eye, power of accommodation, defects, refraction through prism'},
    {ch:11, title:'Electricity', desc:'Electric current, potential difference, Ohm\'s law, circuits, power'},
    {ch:12, title:'Magnetic Effects of Electric Current', desc:'Magnetic field, Fleming\'s rules, electric motor, generator, domestic wiring'},
    {ch:13, title:'Our Environment', desc:'Ecosystem, food chain, environmental problems, ozone layer'},
    {ch:14, title:'Management of Natural Resources', desc:'Forests, water, coal, petroleum, the 3Rs'},
  ],
  '10-Social Science': [
    {ch:1, title:'The Rise of Nationalism in Europe', desc:'Frederic Sorrieu, nation-states, French Revolution, German unification'},
    {ch:2, title:'Nationalism in India', desc:'Non-cooperation movement, Civil Disobedience, Sense of collective belonging'},
    {ch:3, title:'The Making of a Global World', desc:'Silk routes, trade, colonialism, Bretton Woods, post-WWII economy'},
    {ch:4, title:'The Age of Industrialisation', desc:'Proto-industrialisation, factories, Manchester, Indian textiles'},
    {ch:5, title:'Print Culture and the Modern World', desc:'Print revolution, press and novel, India and print'},
    {ch:6, title:'Resources and Development', desc:'Types of resources, resource planning, land use, soil types'},
    {ch:7, title:'Forest and Wildlife Resources', desc:'Types of forests, depletion, conservation, wildlife acts'},
    {ch:8, title:'Water Resources', desc:'Water scarcity, dams, rainwater harvesting'},
    {ch:9, title:'Agriculture', desc:'Types of farming, food crops, commercial crops, food security'},
    {ch:10, title:'Minerals and Energy Resources', desc:'Types of minerals, energy sources, conservation'},
    {ch:11, title:'Manufacturing Industries', desc:'Industries and economy, industrial pollution, special economic zones'},
    {ch:12, title:'Life Lines of National Economy', desc:'Transport, communication, international trade'},
    {ch:13, title:'Power Sharing', desc:'Belgium and Sri Lanka, forms of power sharing, federalism'},
    {ch:14, title:'Federalism', desc:'Indian federalism, decentralisation, local bodies'},
    {ch:15, title:'Democracy and Diversity', desc:'Social divisions, politics of social divisions'},
    {ch:16, title:'Development', desc:'What is development, national development, HDI, sustainability'},
    {ch:17, title:'Sectors of the Indian Economy', desc:'Primary, secondary, tertiary sectors, organised and unorganised'},
  ],
  '10-English': [
    {ch:1, title:'A Letter to God', desc:'Lencho\'s faith, irony, comprehension'},
    {ch:2, title:'Nelson Mandela: Long Walk to Freedom', desc:'Apartheid, freedom struggle, autobiography'},
    {ch:3, title:'Two Stories about Flying', desc:'His First Flight and Black Aeroplane, courage, imagination'},
    {ch:4, title:'From the Diary of Anne Frank', desc:'Holocaust, diary writing, comprehension'},
    {ch:5, title:'Glimpses of India', desc:'A Baker from Goa, Coorg, Tea from Assam, India\'s diversity'},
    {ch:6, title:'Mijbil the Otter', desc:'Gavin Maxwell, keeping an unusual pet'},
    {ch:7, title:'Madam Rides the Bus', desc:'Tamil story, Valli\'s curiosity and adventure'},
    {ch:8, title:'The Sermon at Benares', desc:'Gautama Buddha, sorrow and acceptance'},
    {ch:9, title:'The Proposal', desc:'Anton Chekhov drama, humour, quarrelling neighbours'},
  ],
  '10-Hindi': [
    {ch:1, title:'सूरदास के पद', desc:'सूरदास, कृष्ण भक्ति और वात्सल्य'},
    {ch:2, title:'राम-लक्ष्मण-परशुराम संवाद', desc:'तुलसीदास, रामचरितमानस, वीर रस'},
    {ch:3, title:'देव के सवैये और कवित्त', desc:'देव, ब्रजभाषा काव्य, श्रृंगार रस'},
    {ch:4, title:'आत्मकथ्य', desc:'जयशंकर प्रसाद, छायावादी कविता'},
    {ch:5, title:'उत्साह और अट नहीं रही', desc:'सूर्यकांत त्रिपाठी निराला, प्रकृति चित्रण'},
    {ch:6, title:'नेताजी का चश्मा', desc:'कहानी - स्वयं प्रकाश, देशभक्ति'},
    {ch:7, title:'बालगोबिन भगत', desc:'रेखाचित्र - रामवृक्ष बेनीपुरी, सादगी और भक्ति'},
    {ch:8, title:'लखनवी अंदाज़', desc:'व्यंग्य - यशपाल, नवाबी संस्कृति'},
    {ch:9, title:'मानवीय करुणा की दिव्य चमक', desc:'संस्मरण - सर्वेश्वर दयाल सक्सेना, फादर बुल्के'},
    {ch:10, title:'एक कहानी यह भी', desc:'आत्मकथ्य - मन्नू भंडारी, नारी चेतना'},
  ],

  // ─── CLASS 11 ─────────────────────────────────────────────
  '11-Mathematics': [
    {ch:1, title:'Sets', desc:'Sets and their representations, types of sets, Venn diagrams, operations'},
    {ch:2, title:'Relations and Functions', desc:'Ordered pairs, Cartesian product, relations, types of functions'},
    {ch:3, title:'Trigonometric Functions', desc:'Angles, trigonometric functions, identities, signs in quadrants'},
    {ch:4, title:'Complex Numbers and Quadratic Equations', desc:'Complex numbers, modulus, conjugate, quadratic equations with complex roots'},
    {ch:5, title:'Linear Inequalities', desc:'Algebraic and graphical solutions, system of linear inequalities'},
    {ch:6, title:'Permutations and Combinations', desc:'Fundamental principle, permutations, combinations, applications'},
    {ch:7, title:'Binomial Theorem', desc:'Binomial theorem for positive integral index, general and middle terms'},
    {ch:8, title:'Sequences and Series', desc:'AP and GP, relationships between AM and GM'},
    {ch:9, title:'Straight Lines', desc:'Slope, equations of lines, angle between lines, distance from a point'},
    {ch:10, title:'Conic Sections', desc:'Circle, parabola, ellipse, hyperbola, standard equations'},
    {ch:11, title:'Introduction to Three-Dimensional Geometry', desc:'Coordinate axes, distance formula, section formula in 3D'},
    {ch:12, title:'Limits and Derivatives', desc:'Intuitive idea of derivatives, limits, algebra of limits, derivatives'},
    {ch:13, title:'Statistics', desc:'Measures of dispersion, mean deviation, variance, standard deviation'},
    {ch:14, title:'Probability', desc:'Random experiments, events, axiomatic approach, addition rule'},
  ],
  '11-Physics': [
    {ch:1, title:'Physical World', desc:'Physics, technology and society, scope and excitement of physics'},
    {ch:2, title:'Units and Measurements', desc:'International System of Units, measurement of length, mass, time, errors'},
    {ch:3, title:'Motion in a Straight Line', desc:'Position, path length, displacement, velocity, acceleration, kinematic equations'},
    {ch:4, title:'Motion in a Plane', desc:'Scalars and vectors, resolution, projectile motion, circular motion'},
    {ch:5, title:'Laws of Motion', desc:'Aristotle\'s fallacy, Newton\'s three laws, momentum, conservation'},
    {ch:6, title:'Work, Energy and Power', desc:'Work-energy theorem, potential energy, conservation of mechanical energy'},
    {ch:7, title:'System of Particles and Rotational Motion', desc:'Centre of mass, moment of inertia, theorems, rolling motion'},
    {ch:8, title:'Gravitation', desc:'Kepler\'s laws, universal gravitation, acceleration due to gravity, satellites'},
    {ch:9, title:'Mechanical Properties of Solids', desc:'Elastic behaviour, stress, strain, Hooke\'s law, moduli of elasticity'},
    {ch:10, title:'Mechanical Properties of Fluids', desc:'Pressure, viscosity, surface tension, Bernoulli\'s theorem'},
    {ch:11, title:'Thermal Properties of Matter', desc:'Temperature, heat, thermal expansion, specific heat, calorimetry, conduction'},
    {ch:12, title:'Thermodynamics', desc:'Thermal equilibrium, laws of thermodynamics, heat engines, refrigerators'},
    {ch:13, title:'Kinetic Theory', desc:'Molecular nature of matter, kinetic theory of gases, degrees of freedom'},
    {ch:14, title:'Oscillations', desc:'Periodic and oscillatory motion, SHM, energy in SHM, pendulum'},
    {ch:15, title:'Waves', desc:'Transverse and longitudinal waves, speed, superposition, standing waves, beats'},
  ],
  '11-Chemistry': [
    {ch:1, title:'Some Basic Concepts of Chemistry', desc:'Importance of chemistry, properties of matter, atoms and molecules, mole concept'},
    {ch:2, title:'Structure of Atom', desc:'Sub-atomic particles, atomic models, quantum mechanics, orbitals, electronic configuration'},
    {ch:3, title:'Classification of Elements and Periodicity', desc:'Mendeleev\'s and modern periodic table, trends in properties'},
    {ch:4, title:'Chemical Bonding and Molecular Structure', desc:'Ionic, covalent, metallic bonds, VSEPR, hybridisation, molecular orbital theory'},
    {ch:5, title:'States of Matter', desc:'Intermolecular forces, gas laws, kinetic theory, liquids'},
    {ch:6, title:'Thermodynamics', desc:'System and surroundings, enthalpy, entropy, Gibbs energy, spontaneity'},
    {ch:7, title:'Equilibrium', desc:'Chemical and ionic equilibrium, Le Chatelier\'s principle, pH, buffer solutions'},
    {ch:8, title:'Redox Reactions', desc:'Oxidation and reduction, electrode reactions, balancing redox equations'},
    {ch:9, title:'Hydrogen', desc:'Position in periodic table, occurrence, isotopes, properties, compounds'},
    {ch:10, title:'The s-Block Elements', desc:'Group 1 and 2 elements, properties, compounds, biological importance'},
    {ch:11, title:'The p-Block Elements', desc:'Groups 13 and 14, boron family, carbon family, allotropes'},
    {ch:12, title:'Organic Chemistry: Basic Principles', desc:'General introduction, IUPAC nomenclature, isomerism, reaction mechanisms'},
    {ch:13, title:'Hydrocarbons', desc:'Classification, alkanes, alkenes, alkynes, benzene, carcinogenicity'},
    {ch:14, title:'Environmental Chemistry', desc:'Environmental pollution, atmospheric, water and soil pollution'},
  ],
  '11-Biology': [
    {ch:1, title:'The Living World', desc:'What is living, taxonomy, systematics, classification of living organisms'},
    {ch:2, title:'Biological Classification', desc:'Kingdoms, Monera, Protista, Fungi, Plantae, Animalia'},
    {ch:3, title:'Plant Kingdom', desc:'Algae, bryophytes, pteridophytes, gymnosperms, angiosperms, plant life cycles'},
    {ch:4, title:'Animal Kingdom', desc:'Basis of classification, invertebrates to vertebrates, salient features'},
    {ch:5, title:'Morphology of Flowering Plants', desc:'Root, stem, leaf, flower, fruit, seed, semi-technical descriptions'},
    {ch:6, title:'Anatomy of Flowering Plants', desc:'Tissues, tissue systems, internal organisation of stem, leaf, root'},
    {ch:7, title:'Structural Organisation in Animals', desc:'Morphology and anatomy of frog, earthworm, cockroach'},
    {ch:8, title:'Cell: The Unit of Life', desc:'Cell theory, prokaryotic and eukaryotic cells, cell organelles in detail'},
    {ch:9, title:'Biomolecules', desc:'Micromolecules and macromolecules, proteins, polysaccharides, nucleic acids, enzymes'},
    {ch:10, title:'Cell Cycle and Cell Division', desc:'Cell cycle, mitosis, meiosis, significance'},
    {ch:11, title:'Transport in Plants', desc:'Means of transport, water potential, osmosis, transpiration, phloem transport'},
    {ch:12, title:'Mineral Nutrition', desc:'Essential elements, deficiency symptoms, nitrogen metabolism'},
    {ch:13, title:'Photosynthesis in Higher Plants', desc:'Light reactions, electron transport, photophosphorylation, Calvin cycle'},
    {ch:14, title:'Respiration in Plants', desc:'Glycolysis, fermentation, aerobic respiration, Krebs cycle, electron transport'},
    {ch:15, title:'Plant Growth and Development', desc:'Growth phases, differentiation, plant hormones, photoperiodism, vernalisation'},
  ],
  '11-English': [
    {ch:1, title:'The Portrait of a Lady', desc:'Khushwant Singh, relationship with grandmother, change over time'},
    {ch:2, title:'We\'re Not Afraid to Die', desc:'Sea voyage, survival, courage and teamwork'},
    {ch:3, title:'Discovering Tut: the Saga Continues', desc:'King Tut, CT scan, Egyptology'},
    {ch:4, title:'Landscape of the Soul', desc:'Chinese painting, art and perspective, the eye of the beholder'},
    {ch:5, title:'The Ailing Planet: the Green Movement\'s Role', desc:'Environment, sustainable development, green movement'},
    {ch:6, title:'The Browning Version', desc:'Terence Rattigan drama, a teacher\'s private life and self-realisation'},
    {ch:7, title:'The Adventure', desc:'Science fiction, Prof Gaitonde, parallel universe, history'},
    {ch:8, title:'Silk Road', desc:'Nick Middleton, travel in Tibet, Kailash Mansarovar yatra'},
  ],

  // ─── CLASS 12 ─────────────────────────────────────────────
  '12-Mathematics': [
    {ch:1, title:'Relations and Functions', desc:'Types of relations, types of functions, composition, invertible functions'},
    {ch:2, title:'Inverse Trigonometric Functions', desc:'Basic concepts, properties, principal value branch'},
    {ch:3, title:'Matrices', desc:'Matrix order, types, operations, transpose, invertible matrices'},
    {ch:4, title:'Determinants', desc:'Determinant of a matrix, cofactors, adjoint, inverse, applications'},
    {ch:5, title:'Continuity and Differentiability', desc:'Continuity, differentiability, exponential and logarithmic functions, MVT'},
    {ch:6, title:'Application of Derivatives', desc:'Rate of change, increasing/decreasing functions, maxima and minima'},
    {ch:7, title:'Integrals', desc:'Integration as inverse of differentiation, methods of integration, definite integral'},
    {ch:8, title:'Application of Integrals', desc:'Area under simple curves, area between two curves'},
    {ch:9, title:'Differential Equations', desc:'Basic concepts, order, degree, formation, methods of solving'},
    {ch:10, title:'Vector Algebra', desc:'Types of vectors, addition, multiplication by scalar, dot and cross product'},
    {ch:11, title:'Three-Dimensional Geometry', desc:'Direction cosines, equations of lines and planes, angle between them'},
    {ch:12, title:'Linear Programming', desc:'Linear programming problem, graphical method, simplex method'},
    {ch:13, title:'Probability', desc:'Conditional probability, multiplication rule, Bayes\' theorem, random variable'},
  ],
  '12-Physics': [
    {ch:1, title:'Electric Charges and Fields', desc:'Electric charge, Coulomb\'s law, electric field, Gauss\'s law'},
    {ch:2, title:'Electrostatic Potential and Capacitance', desc:'Electric potential, capacitors, energy stored, dielectrics'},
    {ch:3, title:'Current Electricity', desc:'Electric current, Ohm\'s law, EMF, Kirchhoff\'s laws, Wheatstone bridge'},
    {ch:4, title:'Moving Charges and Magnetism', desc:'Oersted\'s experiment, Biot-Savart law, Ampere\'s law, cyclotron'},
    {ch:5, title:'Magnetism and Matter', desc:'Bar magnet, Gauss\'s law for magnetism, properties of magnetic materials'},
    {ch:6, title:'Electromagnetic Induction', desc:'Faraday\'s and Lenz\'s law, motional EMF, eddy currents, inductance'},
    {ch:7, title:'Alternating Current', desc:'AC voltage applied to resistor, LC oscillations, transformer, power factor'},
    {ch:8, title:'Electromagnetic Waves', desc:'Displacement current, Maxwell\'s equations, EM spectrum'},
    {ch:9, title:'Ray Optics and Optical Instruments', desc:'Reflection, refraction, total internal reflection, lenses, optical instruments'},
    {ch:10, title:'Wave Optics', desc:'Wavefront, Huygens\' principle, interference, diffraction, polarisation'},
    {ch:11, title:'Dual Nature of Radiation and Matter', desc:'Photoelectric effect, Einstein\'s equation, de Broglie wavelength'},
    {ch:12, title:'Atoms', desc:'Alpha particle scattering, Rutherford model, Bohr model, energy levels'},
    {ch:13, title:'Nuclei', desc:'Atomic masses, nuclear binding energy, radioactivity, nuclear reactions'},
    {ch:14, title:'Semiconductor Electronics', desc:'Semiconductors, p-n junction, transistor, logic gates, integrated circuits'},
  ],
  '12-Chemistry': [
    {ch:1, title:'The Solid State', desc:'General characteristics, crystal systems, imperfections, electrical properties'},
    {ch:2, title:'Solutions', desc:'Types of solutions, concentration, Raoult\'s law, colligative properties, osmosis'},
    {ch:3, title:'Electrochemistry', desc:'Electrochemical cells, Nernst equation, EMF, batteries, corrosion'},
    {ch:4, title:'Chemical Kinetics', desc:'Rate of reaction, factors affecting rate, activation energy, catalysis'},
    {ch:5, title:'Surface Chemistry', desc:'Adsorption, colloids, emulsions, catalysis'},
    {ch:6, title:'General Principles of Isolation of Elements', desc:'Occurrence, extraction methods, refining'},
    {ch:7, title:'The p-Block Elements', desc:'Groups 15-18: nitrogen family, oxygen family, halogens, noble gases'},
    {ch:8, title:'The d and f Block Elements', desc:'Transition elements, inner transition elements, lanthanoids, actinoids'},
    {ch:9, title:'Coordination Compounds', desc:'Werner\'s theory, nomenclature, isomerism, bonding, stability'},
    {ch:10, title:'Haloalkanes and Haloarenes', desc:'Classification, nomenclature, properties, SN1 and SN2 reactions'},
    {ch:11, title:'Alcohols, Phenols and Ethers', desc:'Classification, nomenclature, physical and chemical properties'},
    {ch:12, title:'Aldehydes, Ketones and Carboxylic Acids', desc:'Nomenclature, preparation, reactions, uses'},
    {ch:13, title:'Amines', desc:'Nomenclature, classification, methods of preparation, chemical reactions'},
    {ch:14, title:'Biomolecules', desc:'Carbohydrates, proteins, enzymes, vitamins, nucleic acids, hormones'},
    {ch:15, title:'Polymers', desc:'Classification, methods of polymerisation, biodegradable polymers'},
    {ch:16, title:'Chemistry in Everyday Life', desc:'Drugs, food additives, cleansing agents, polymers in medicine'},
  ],
  '12-Biology': [
    {ch:1, title:'Reproduction in Organisms', desc:'Modes of reproduction, asexual reproduction, sexual reproduction'},
    {ch:2, title:'Sexual Reproduction in Flowering Plants', desc:'Flower structure, pollination, fertilisation, seeds, fruits'},
    {ch:3, title:'Human Reproduction', desc:'Male and female reproductive system, gametogenesis, fertilisation, pregnancy'},
    {ch:4, title:'Reproductive Health', desc:'Problems and strategies, population explosion, birth control, STIs'},
    {ch:5, title:'Principles of Inheritance and Variation', desc:'Mendel\'s laws, chromosomal theory, sex determination, mutation'},
    {ch:6, title:'Molecular Basis of Inheritance', desc:'DNA structure, replication, transcription, translation, gene regulation'},
    {ch:7, title:'Evolution', desc:'Origin of life, theories of evolution, evidence, adaptive radiation, human evolution'},
    {ch:8, title:'Human Health and Disease', desc:'Pathogens, immunity, AIDS, cancer, drugs and alcohol abuse'},
    {ch:9, title:'Strategies for Enhancement in Food Production', desc:'Animal husbandry, plant breeding, tissue culture, biofortification'},
    {ch:10, title:'Microbes in Human Welfare', desc:'Microbes in household, industry, sewage treatment, biogas'},
    {ch:11, title:'Biotechnology: Principles and Processes', desc:'Tools of recombinant DNA technology, PCR, cloning'},
    {ch:12, title:'Biotechnology and its Applications', desc:'Transgenic plants and animals, ethical issues, bio-safety'},
    {ch:13, title:'Organisms and Populations', desc:'Organism and its environment, populations, interactions'},
    {ch:14, title:'Ecosystem', desc:'Ecosystem structure, productivity, decomposition, energy flow, nutrient cycling'},
    {ch:15, title:'Biodiversity and Conservation', desc:'Biodiversity patterns, importance, loss, conservation strategies'},
    {ch:16, title:'Environmental Issues', desc:'Air, water, soil pollution, global warming, deforestation, remediation'},
  ],
  '12-English': [
    {ch:1, title:'The Last Lesson', desc:'Alphonse Daudet, French identity, war and language'},
    {ch:2, title:'Lost Spring', desc:'Anees Jung, poverty, child labour in India'},
    {ch:3, title:'Deep Water', desc:'William Douglas, fear and courage, swimming'},
    {ch:4, title:'The Rattrap', desc:'Selma Lagerlöf, kindness transforms a cynical person'},
    {ch:5, title:'Indigo', desc:'Louis Fischer, Gandhi and Champaran Satyagraha'},
    {ch:6, title:'Poets and Pancakes', desc:'Asokamitran, film industry, Gemini Studios'},
    {ch:7, title:'The Interview', desc:'Christopher Silvester, forms and purposes of interview'},
    {ch:8, title:'Going Places', desc:'A.R. Barton, teenage fantasies, unrealistic dreams'},
    {ch:9, title:'My Mother at Sixty-Six', desc:'Kamala Das, ageing and separation'},
    {ch:10, title:'An Elementary School Classroom in a Slum', desc:'Stephen Spender, poverty, education'},
  ],
};

async function main() {
  // Clear existing lectures first
  await runSQL('DELETE FROM lectures;', 'clear-lectures');

  let total = 0;
  for (const [key, chapters] of Object.entries(lectureData)) {
    const [cls, ...subjectParts] = key.split('-');
    const subject = subjectParts.join('-');
    const classLevel = parseInt(cls);

    const rows = chapters.map((c, i) => ({
      subject: subject,
      cls: classLevel,
      ch: c.ch,
      title: c.title,
      desc: c.desc,
      dur: 30,
      order: c.ch,
    }));

    const sql = buildLectureInserts(rows);
    await runSQL(sql, `lectures-${key}`);
    total += rows.length;
  }

  console.log(`\n✅ Phase 2a complete: ${total} lectures seeded`);
}

main().catch(e => { console.error(e); process.exit(1); });
